name: MLOps Full Workflow

on:
  push:
    branches:
      - main

jobs:
  train_all_datasets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow scikit-learn pandas dvc

      - name: Pull DVC data
        run: |
          dvc pull

      - name: Train models on all datasets
        run: |
          for ds in data/raw/credit_risk_dataset_v1.csv \
                    data/raw/credit_risk_dataset_v2.csv \
                    data/raw/credit_risk_dataset_v3.csv
          do
            echo "Training with $ds"
            python src/train_model.py --dataset $ds
          done
